"""CLASSIFIER-FREE placement bound.

For a cluster (E = equations, S = every atom whose whole equation set lies inside E) the number
of failing equations is  |{e in E : M_e . v != 0}|  where v is the atom-value vector.  Minimising
that over ALL nonzero rational v is a minimum-weight-codeword problem in the code generated by the
columns of M.  It IGNORES which atoms are actually settable and ignores integrality, so it is a
RELAXATION: the true cost is >= this number.  Any cluster whose min weight is >= 7 therefore
cannot beat the 39,026 deliverable, with no settability classifier involved at all.

Min weight is attained on a v annihilating |S|-1 independent rows, so we enumerate those.
"""
import sys, os, json, collections, itertools, time
from fractions import Fraction
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from close4 import *
W=os.path.dirname(os.path.abspath(__file__))+'/'
AE={a:frozenset(L.atom2eq.get(a,{})) for a in range(L.NA)}
eq2atoms=collections.defaultdict(set)
for a,es in AE.items():
    for e in es: eq2atoms[e].add(a)
def inside(E):
    c=set()
    for e in E: c|=eq2atoms[e]
    return sorted(a for a in c if AE[a]<=E)
def kernel_vec(rows,ncol):
    """one nonzero vector annihilating the given rows, or None if only 0."""
    A=[[Fraction(x) for x in r] for r in rows]
    piv=[]; r=0
    for c in range(ncol):
        p=next((i for i in range(r,len(A)) if A[i][c]!=0),None)
        if p is None: continue
        A[r],A[p]=A[p],A[r]; pv=A[r][c]; A[r]=[x/pv for x in A[r]]
        for i in range(len(A)):
            if i!=r and A[i][c]!=0:
                f=A[i][c]; A[i]=[x-f*y for x,y in zip(A[i],A[r])]
        piv.append(c); r+=1
        if r==len(A): break
    free=[c for c in range(ncol) if c not in piv]
    if not free: return None
    f0=free[0]; v=[Fraction(0)]*ncol; v[f0]=Fraction(1)
    for i,c in enumerate(piv): v[c]=-A[i][f0]
    return v
def minweight(E,S,cap=200000):
    E=sorted(E); n=len(S)
    if n==0: return None,None
    M=[[L.eq_atoms[e][2].get(a,0) for a in S] for e in E]
    best=(len(E)+1,None)
    if n==1:
        w=sum(1 for r in M if r[0]!=0)
        return w,[1]
    cnt=0
    for combo in itertools.combinations(range(len(E)),n-1):
        cnt+=1
        if cnt>cap: return None,None            # too big: skip (reported separately)
        v=kernel_vec([M[i] for i in combo],n)
        if v is None: continue
        w=sum(1 for r in M if sum(Fraction(x)*y for x,y in zip(r,v))!=0)
        if 0<w<best[0]: best=(w,v)
    return best[0] if best[1] is not None else None, best[1]

print('CALIBRATION on the 39,026 deliverable cluster (observed failing = 7)')
D=[22229,22230,35758,35759,35760,35761,35762]
E=frozenset().union(*[AE[a] for a in D]); S=inside(E)
w,v=minweight(E,S)
print('  |E|=%d |S|=%d  ->  min weight = %s   (observed 7)'%(len(E),len(S),w))
CAL = (w==7)
print('  classifier-free bound %s the deliverable exactly'%('REPRODUCES' if CAL else 'does NOT reproduce'))

print('\nGLOBAL SCAN')
t0=time.time()
seen=set(); rows=[]; skipped=0
# (a) every single-atom cluster
for a in range(L.NA):
    Ea=AE[a]
    if not (1<=len(Ea)<=15): continue
    if Ea in seen: continue
    seen.add(Ea)
    Sa=inside(Ea)
    if len(Sa)>9: skipped+=1; continue
    w,_=minweight(Ea,Sa)
    if w is None: skipped+=1; continue
    rows.append((w,len(Ea),len(Sa),('single',a)))
print('  single-atom clusters: %d distinct, %.0fs'%(len(rows),time.time()-t0))
# (b) unions of two handle-definition atoms sharing an equation (the deliverable's cluster is
#     a union, so single-atom seeds alone would miss that shape)
v0=[0]*L.NVARS
_o2,_F,_fw,_C=mk(())
_fw(v0)
WIR={u for u in range(L.NVARS) if v0[u]==P}
FREE0=set(u for u in range(L.NVARS) if u not in outs)
HD=[]
for a,(c,t) in L.atom_out.items():
    Pp=L.polys[a]
    if len(Pp)!=2: continue
    q=[m for m in Pp if len(m)==2]
    if len(q)!=1: continue
    ws=set(q[0])
    if len(ws&WIR)==1 and len((ws-WIR)&FREE0)==1: HD.append(a)
HD=set(HD)
print('  handle-definition atoms: %d'%len(HD))
pairs=set()
for e,ats in eq2atoms.items():
    h=[a for a in ats if a in HD]
    for x,y in itertools.combinations(sorted(h),2): pairs.add((x,y))
print('  candidate HD pairs sharing an equation: %d'%len(pairs))
np_=0
import time as _t
_T=_t.time()
for (x,y) in pairs:
    if _t.time()-_T>420: print('  [pair phase time-capped]',flush=True); break
    Eu=AE[x]|AE[y]
    if len(Eu)>12 or Eu in seen: continue
    seen.add(Eu)
    Su=inside(Eu)
    if len(Su)>7: skipped+=1; continue
    w,_=minweight(Eu,Su)
    if w is None: skipped+=1; continue
    rows.append((w,len(Eu),len(Su),('pair',x,y))); np_+=1
print('  pair clusters scored: %d   skipped(too large): %d   %.0fs'%(np_,skipped,time.time()-t0))
rows.sort()
print('\nBEST 20 CLUSTERS BY CLASSIFIER-FREE MIN WEIGHT (lower = cheaper defect placement):')
for r in rows[:20]:
    print('   minweight=%-3d |E|=%-3d |S|=%-3d  %s'%r)
best=[r for r in rows if r[0]<7]
print('\nclusters with min weight < 7 (would beat 39,026): %d'%len(best))
for r in best[:40]: print('   *** ',r)
json.dump([[r[0],r[1],r[2],list(r[3])] for r in rows[:800]],open(W+'minweight.json','w'))
print('\nhistogram of min weight:',dict(sorted(collections.Counter(r[0] for r in rows).items())[:12]))
