#!/usr/bin/env python3
"""Agent AB: the other two soft verdicts, §6 (analytic) and §9.12 (Groebner), given a real look."""
import math
from math import comb, log2
p=2**256-2**32-977
print("== §6 ANALYTIC -- upgrading a heuristic threshold to a structural argument ==")
print(" Any equidistribution statement has the shape")
print("    #{k in W : kG in A}  =  |W|*|A|/N  +  E,      E = the discrepancy / error term.")
print(" To DECIDE membership of ONE target T (|A| = 1) the estimate must resolve a count of 0 vs 1,")
print(" i.e. it needs  E < 1.")
print(" Every known bound in this line (Shparlinski; Lange-Shparlinski; Konyagin) has")
print("    E  >=  ~sqrt(p)  ~  2^128   or   E >= |W|^(1-delta),")
print(" both astronomically larger than 1.  So no such theorem can resolve a single point.")
print()
print(" And the decisive structural point, which is not a threshold argument at all:")
print("   a PERFECT equidistribution theorem (E = 0) would say each target is hit")
print("   |W|/N times on average -- i.e. the weight class spreads UNIFORMLY over targets, so")
print("   membership of any given T is exactly as likely as for any other T.")
print("   ** The stronger the equidistribution result, the LESS it says about one instance. **")
print("   Only a BIAS could help, and it would have to be a bias resolvable at one point,")
print("   which is the opposite of what this literature proves.")
print(" VERDICT §6: still DEAD, but now for a structural reason rather than my heuristic threshold.")
print()
print("== §9.12 GROEBNER / elimination with a term order -- the honest look ==")
print(" Model: 256 boolean selectors s_i, a 256-step conditional-addition chain over F_p,")
print(" target kG = T.  Unique solution.  Any complete algebraic method must beat 2^126.5 to matter.")
print()
print(" Macaulay matrix width at degree d in n=256 boolean variables (monomials, squarefree):")
for d in (2,3,4,8,16,32,64,128):
    print("    d=%3d :  C(256,<=d) = 2^%.1f columns"%(d,log2(sum(comb(256,j) for j in range(d+1)))))
print()
print(" Linear algebra at degree d costs ~ (#columns)^omega with omega~2.37:")
for d in (8,16,24,32):
    c=log2(sum(comb(256,j) for j in range(d+1)))
    print("    d=%3d :  2^%.1f  %s"%(d,2.37*c,"<= 2^126.5" if 2.37*c<=126.5 else "> 2^126.5  ALREADY DEAD"))
print()
print(" So elimination is affordable only if the degree of regularity d_reg is <= ~16.")
print(" For a boolean system in n variables with a unique solution and no exploitable structure,")
print(" the standard semi-regular estimate puts d_reg at a constant fraction of n (~0.09n for")
print(" quadratic systems over F_2, i.e. d_reg ~ 23 here, and larger for the mixed F_p/boolean")
print(" system actually present).  d_reg ~ 23 already costs 2^%.1f."%(2.37*log2(sum(comb(256,j) for j in range(24)))))
print()
print(" A term order cannot be the missing ingredient: for elimination to be cheap the ideal would")
print(" have to have low d_reg, which is a property of the IDEAL, not of the order.  A different")
print(" order changes the constant, not the exponent.")
print(" VERDICT §9.12: DEAD on complexity, independently of the campaign's empirical failure.")
print(" Worth at most ONE bounded experiment (Singular, degree-truncated linear algebra on the")
print(" reduced core, measure the actual d_reg) -- and only because measuring d_reg is cheap and")
print(" would replace an estimate with a number.  NOT worth a week.")
