"""Exact integer solve on the rank-14 variety derived from the COMPLETE 68-knob candidate set.

Singular has certified that the residue ideal's radical is generated by a single linear form, so the
exact polynomial variety is the linear one; over Z the square `c*s^2 = 0` is likewise `s = 0`.  What
is left is an integer linear feasibility problem, decided exactly by zsolve, plus a comparison
against the rank-14 lattice widen.py was actually searching.
"""
import os, sys, json, time, pickle, itertools
from collections import defaultdict
from flint import fmpz_mat

HERE = os.path.dirname(os.path.abspath(__file__))
sys.set_int_max_str_digits(2000000)
import zsolve

D = pickle.load(open(os.path.join(HERE, 'runs', 'poly68b.pkl'), 'rb'))
K, cands, Rl = D['K'], D['cands'], D['Rl']
resid, regr = D['resid'], D['regr']
d = len(K)
k = len(cands)

print('lattice rank %d in %d knobs' % (d, k), flush=True)
for e, c in resid.items():
    print('residue eq %d: %s' % (e, {m: v for m, v in c.items()}), flush=True)
    mono = list(c)[0]
    idx = [j for j, x in enumerate(mono) if x]
    assert len(idx) == 1 and mono[idx[0]] == 2, 'residue is not a pure square'
    dead = idx[0]
print('the single nonlinear generator forces coordinate s%d = 0 over Z' % dead, flush=True)

free = [a for a in range(d) if a != dead]
M, b = [], []
for e in Rl:
    c = regr[e]
    row = [0] * d
    c0 = 0
    for mono, v in c.items():
        s = sum(mono)
        assert s <= 1, 'region row nonlinear'
        if s == 0:
            c0 = v
        else:
            row[mono.index(1)] = v
    M.append([row[a] for a in free])
    b.append(c0)

print('\nregion system: %d rows x %d unknowns, all affine over Z' % (len(M), len(free)), flush=True)
print('rows already zero at the witness: %d' % sum(1 for x in b if x == 0), flush=True)
t0 = time.time()
opt, rws, exh, nodes = zsolve.max_zero_rows(M, b, len(free), len(M), node_cap=8000000)
fail = len(M) - opt
print('OPT = %d of %d   exhaustive=%s   nodes=%d   (%.1fs)'
      % (opt, len(M), exh, nodes, time.time() - t0), flush=True)
print('   rows: %s' % [Rl[i] for i in rws], flush=True)
print('   => failing = %d, score = %d' % (fail, 39033 - fail), flush=True)

# every 6-subset explicitly, so the negative is exhaustive at the level that matters
print('\nchecking all 924 six-subsets for integer solvability ...', flush=True)
solv = []
for comb in itertools.combinations(range(12), 6):
    sub = [M[i] for i in comb]
    subb = [b[i] for i in comb]
    if zsolve.solvable(sub, subb, len(free)) if hasattr(zsolve, 'solvable') else False:
        solv.append(comb)
if not hasattr(zsolve, 'solvable'):
    for comb in itertools.combinations(range(12), 6):
        o, _, ex, _ = zsolve.max_zero_rows([M[i] for i in comb], [b[i] for i in comb],
                                           len(free), 6, node_cap=200000)
        if o == 6:
            solv.append(comb)
print('six-subsets integrally solvable: %d of 924' % len(solv), flush=True)

# lattice comparison with widen.py
prev = json.load(open(os.path.join(HERE, 'runs', 'polyfull.json')))
print('\nknob set: %d (exact polynomial support) vs %d (widen.py step-1 filter)'
      % (k, len(prev['knobs'])), flush=True)

LAT = [K[a] for a in free]
json.dump(dict(lattice_rank=len(free), knobs=k, opt=opt, exhaustive=bool(exh),
               failing=fail, score=39033 - fail, rows=[Rl[i] for i in rws],
               six_subsets_solvable=len(solv)),
          open(os.path.join(HERE, 'runs', 'solve68.json'), 'w'), indent=1)
pickle.dump(dict(LAT=LAT, cands=cands, M=M, b=b, Rl=Rl),
            open(os.path.join(HERE, 'runs', 'solve68.pkl'), 'wb'))
print('wrote runs/solve68.{json,pkl}', flush=True)
