"""The exact INTEGER solve on the true variety, and a blast-radius check against widen.py.

Singular says the collateral ideal's radical is generated by linear forms (dim 14 of 16, one
component, degree 2 only because of the non-reduced square).  So the exact polynomial variety is a
LINEAR one, and every integer point of it is an integer point of an explicit rank-14 lattice.  Here:

  * that lattice is built exactly over Z (the square `s^2 = 0` forces `s = 0` over Z as well);
  * the 12 region rows are restricted to it and the maximum integrally-zeroable count is computed
    with zsolve (exact, exhaustive), on the TRUE linear part rather than widen.py's step-1 secant;
  * the lattice is compared to widen.py's, so the blast radius of the correction is measured, not
    assumed;
  * collateral budgets |W| = 1, 2 are re-run exactly on the polynomial model.
"""
import os, sys, json, time, pickle, itertools
from collections import defaultdict
from flint import fmpz_mat

HERE = os.path.dirname(os.path.abspath(__file__))
sys.set_int_max_str_digits(2000000)
import zsolve

D = pickle.load(open(os.path.join(HERE, 'runs', 'kerquad2.pkl'), 'rb'))
d, gens, K0, Rl, knobs = D['d'], D['gens'], D['K0'], D['R'], D['knobs']
COL = [g for g in gens if not g[4]]
REG = [g for g in gens if g[4]]


def main():
    print('=== exact integer constraints from the surviving collateral generators ===', flush=True)
    forced = set()
    for lab, c0, L, Q, isreg in COL:
        nzl = [a for a, c in enumerate(L) if c]
        if c0 == 0 and len(nzl) == 1 and not Q:
            forced.add(nzl[0])
            print('   %-8s  %d*s%d = 0  -> s%d = 0' % (lab, L[nzl[0]], nzl[0], nzl[0]), flush=True)
        elif c0 == 0 and not nzl and len(Q) == 1:
            (a, b), c = list(Q.items())[0]
            if a == b:
                forced.add(a)
                print('   %-8s  %d*s%d^2 = 0 -> s%d = 0  (square: same over Z as over Q)'
                      % (lab, c, a, a), flush=True)
            else:
                print('   %-8s  %d*s%d*s%d = 0 -> BRANCHES' % (lab, c, a, b), flush=True)
        else:
            print('   %-8s  general: const=%s lin=%d quad=%d' % (lab, c0 != 0, len(nzl), len(Q)),
                  flush=True)
    free = [a for a in range(d) if a not in forced]
    print('   variables forced to 0: %d -> %s' % (len(forced), sorted(forced)), flush=True)
    print('   remaining lattice rank: %d' % len(free), flush=True)

    # lattice in knob space
    LAT = [K0[a] for a in free]
    k = len(knobs)

    # region rows restricted to the free coordinates
    M = []
    b = []
    for lab, c0, L, Q, isreg in REG:
        assert not Q, 'region row unexpectedly quadratic'
        M.append([L[a] for a in free])
        b.append(c0)
    n = len(free)
    print('\n=== region system on the exact variety: %d rows x %d unknowns, all affine ==='
          % (len(M), n), flush=True)
    z0 = sum(1 for x in b if x == 0)
    print('rows already zero at the witness: %d' % z0, flush=True)
    t0 = time.time()
    opt, rows, exh, nodes = zsolve.max_zero_rows(M, b, n, len(M), node_cap=2000000)
    print('OPT (max integrally zeroable region rows) = %d of %d   exhaustive=%s  nodes=%d  (%.1fs)'
          % (opt, len(M), exh, nodes, time.time() - t0), flush=True)
    print('   best row set: %s' % [Rl[i] for i in rows], flush=True)
    fail = len(M) - opt
    print('   => failing = %d, score = %d' % (fail, 39033 - fail), flush=True)

    # ---- blast radius: is this the same lattice widen.py used? ------------------------------
    print('\n=== blast radius vs widen.py (step-1 secant, kernel dim 14) ===', flush=True)
    import widen, optN
    st = optN.make(optN.WIT)
    b0 = optN.build(st)
    rowsW, bW, MW, kW = widen.build_wide(st, b0['R'], knobs,
                                         [e for e in D['LIN']] + [e for e in D['QUA']])
    nR = len(b0['R'])
    KW = widen.int_kernel([MW[i] for i in range(nR, len(rowsW))])
    print('widen kernel dim %d ; exact-variety lattice rank %d' % (len(KW), len(LAT)), flush=True)
    A = fmpz_mat([[int(x) for x in v] for v in LAT])
    B = fmpz_mat([[int(x) for x in v] for v in KW])
    HA = [r for r in A.hnf().tolist() if any(r)]
    HB = [r for r in B.hnf().tolist() if any(r)]
    same = (len(HA) == len(HB)) and all([int(x) for x in HA[i]] == [int(x) for x in HB[i]]
                                        for i in range(len(HA)))
    print('same lattice (HNF equal): %s' % same, flush=True)
    if not same:
        # containment test both ways via HNF of the union
        U = fmpz_mat([[int(x) for x in v] for v in LAT + KW])
        HU = [r for r in U.hnf().tolist() if any(r)]
        print('rank of the union: %d (exact %d, widen %d)' % (len(HU), len(HA), len(HB)),
              flush=True)

    # ---- collateral budgets on the exact model ----------------------------------------------
    print('\n=== collateral budgets, exact polynomial model ===', flush=True)
    LINrows = D['LIN']
    res = {'W0': dict(opt=opt, failing=fail, score=39033 - fail, exh=exh)}
    from kerquad import int_kernel_columns
    from kerquad2 import PARTS, restrict
    best = (fail, 0, None)
    for W in (1, 2):
        t0 = time.time()
        bestg = -1
        bestW = None
        cnt = 0
        allrows = list(D['LIN']) + list(D['QUA'])
        for drop in itertools.combinations(range(len(allrows)), W):
            dropset = set(allrows[i] for i in drop)
            keepL = [e for e in D['LIN'] if e not in dropset]
            Kw = int_kernel_columns([PARTS[e][1] for e in keepL], k)
            frc = set()
            ok = True
            for e in D['QUA']:
                if e in dropset:
                    continue
                c0, L, Q = restrict(e, Kw)
                nzl = [a for a, c in enumerate(L) if c]
                if c0 == 0 and len(nzl) == 1 and not Q:
                    frc.add(nzl[0])
                elif c0 == 0 and not nzl and len(Q) == 1 and list(Q)[0][0] == list(Q)[0][1]:
                    frc.add(list(Q)[0][0])
                elif c0 == 0 and not nzl and not Q:
                    pass
                else:
                    ok = False
                    break
            if not ok:
                continue
            fr2 = [a for a in range(len(Kw)) if a not in frc]
            MM, bb = [], []
            for e in Rl:
                c0, L, Q = restrict(e, Kw)
                if Q:
                    ok = False
                    break
                MM.append([L[a] for a in fr2])
                bb.append(c0)
            if not ok:
                continue
            cnt += 1
            g, rws, ex, nd = zsolve.max_zero_rows(MM, bb, len(fr2), len(MM), node_cap=200000)
            if g > bestg:
                bestg = g
                bestW = sorted(dropset)
        f = (len(Rl) - bestg) + W
        print('|W|=%d : %d admissible drop sets, max g = %d, failing = %d, score = %d  (%.1fs)'
              % (W, cnt, bestg, f, 39033 - f, time.time() - t0), flush=True)
        res['W%d' % W] = dict(sets=cnt, g=bestg, failing=f, score=39033 - f, best=bestW)
        if f < best[0]:
            best = (f, W, bestW)

    print('\nBEST over |W| <= 2 on the exact polynomial model: failing = %d, score = %d'
          % (best[0], 39033 - best[0]), flush=True)
    json.dump(dict(forced=sorted(forced), rank=len(free), opt=opt, exh=exh, budgets=res,
                   same_lattice_as_widen=bool(same)),
              open(os.path.join(HERE, 'runs', 'solve14.json'), 'w'), indent=1)


if __name__ == '__main__':
    main()
