"""S10 step 28: GLOBAL handle census over all 42,267 atoms.

For each atom a define its *absorbable lattice*: the subgroup of Z generated by
  { d(atom a)/d(x_u)  :  x_u is a free input whose ONLY atom is a }
i.e. the amounts by which atom a can be shifted at zero cost to every other atom.

  lattice = Z      -> atom is a free knob
  lattice = p*Z    -> atom is p-quantised (the trapdoor's building block)
  lattice = {0}    -> atom is rigid

This is a global structural statement about the instance, and it says exactly
where an escape from the two mod-p congruences could possibly live.
"""
import os, sys, collections, math, json
HERE = os.path.dirname(os.path.abspath(__file__))
LAB = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(LAB, 's9', 'eff'))
sys.path.insert(0, HERE)
import lib as L
import tools as T

P = 2**256 - 2**32 - 977
v = L.load(os.path.join(LAB, 'best', 'new_instance_partial_39026.json'))

solo = collections.defaultdict(list)     # atom -> free vars occurring ONLY there
for u in range(L.NVARS):
    if u in L.definer:
        continue
    ats = L.var_atoms[u]
    if len(ats) == 1:
        solo[ats[0]].append(u)

print(f'free inputs occurring in exactly one atom: {sum(len(x) for x in solo.values())}')
print(f'atoms carrying at least one such handle: {len(solo)}')

kinds = collections.Counter()
free_atoms, pquant, other = [], [], []
for a, us in solo.items():
    g = 0
    for u in us:
        r = T.lin_parts(a, u, v)
        if r is None:
            continue
        g = math.gcd(g, abs(r[0]))
    if g == 0:
        kinds['rigid(dormant handle)'] += 1
    elif g == 1:
        kinds['FREE (lattice = Z)'] += 1; free_atoms.append(a)
    elif g % P == 0:
        kinds[f'p-quantised (g/p = {g//P})'] += 1; pquant.append((a, g // P))
    else:
        kinds[f'other g={g}'] += 1; other.append((a, g))

print('\n=== census ===')
for k, n in kinds.most_common(20):
    print(f'  {k:<34} {n}')

print(f'\natoms with an unquantised (Z) handle : {len(free_atoms)}')
print(f'atoms with a p-quantised handle      : {len(pquant)}')
print(f'atoms with some other granularity    : {len(other)}')
if other:
    print('  examples:', other[:12])

# which of the 12 residual equations contain a Z-handle atom?
NZ = [22229, 22230, 35758, 35759, 35760, 35761, 35762]
EQS = sorted(L.eqs_of_atoms(NZ))
freeset = set(free_atoms)
print('\n=== does any residual equation contain a fully-free atom? ===')
for i in EQS:
    m, sq, co = L.eq_atoms[i]
    hits = [a for a in co if a in freeset]
    print(f'  eq {i:<6} n_atoms={len(co):<3} free-handle atoms: {hits}')

json.dump({'free_atoms': sorted(free_atoms), 'pquant': sorted(pquant),
           'other': sorted(other)}, open(os.path.join(HERE, 'handles.json'), 'w'))
print('\nsaved handles.json')
