#!/usr/bin/env python3
"""K21: order of the chord-composition group generated by the leaf chain, then the
carry DP for a root degeneracy  fold(S_A) = fold(S_B)."""
import sys, os, json, collections
K = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, K)
import fold as FD
P = FD.P


def tonelli(n, p):
    n %= p
    if n == 0: return 0
    if pow(n, (p - 1) // 2, p) != 1: return None
    if p % 4 == 3: return pow(n, (p + 1) // 4, p)
    q, s = p - 1, 0
    while q % 2 == 0: q //= 2; s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1: z += 1
    m, c, t, r = s, pow(z, q, p), pow(n, q, p), pow(n, (q + 1) // 2, p)
    while t != 1:
        i, t2 = 0, t
        while t2 != 1: t2 = t2 * t2 % p; i += 1
        b = pow(c, 1 << (m - i - 1), p)
        m = i; c = b * b % p; t = t * c % p; r = r * b % p
    return r


def isqrt(n):
    x = int(n ** 0.5) + 2
    while x * x > n: x = (x + n // x) // 2
    while (x + 1) * (x + 1) <= n: x += 1
    return x


def cornacchia(d, m):
    """all x,y>0 with x^2 + d y^2 = m, m prime"""
    out = []
    r0 = tonelli(-d % m, m)
    if r0 is None: return out
    for s in (r0, m - r0):
        a, b = m, s
        lim = isqrt(m)
        while b > lim: a, b = b, a % b
        rem = m - b * b
        if rem % d: continue
        y2 = rem // d
        y = isqrt(y2)
        if y * y == y2: out.append((b, y))
    return out


D = FD.points()
ch = json.load(open(K + '/chain.json'))
pts = {int(i): (int(D['leaves'][int(i)]['X']), int(D['leaves'][int(i)]['Y'])) for i in ch['exp']}
bypow = {}
for i_s, e in ch['exp'].items(): bypow[e] = pts[int(i_s)]
G = bypow[0]
T = (int(D['target']['X']), int(D['target']['Y']))


def mulchain(k):
    R = FD.INF; i = 0
    while k:
        if k & 1:
            R = FD.add(R, bypow[i] if i < 256 else None)
        k >>= 1; i += 1
    return R

reps = cornacchia(3, P)
print('p = a^2+3b^2 reps:', reps)
cands = set()
for a, b in reps:
    for t in (2 * a, -2 * a, a + 3 * b, -(a + 3 * b), a - 3 * b, -(a - 3 * b)):
        cands.add(t)
lim = 2 * FD.__dict__.get('isqrt', isqrt)(P)
good = []
for t in sorted(cands):
    if abs(t) > lim: continue
    N = P + 1 - t
    # test N*G == identity using the precomputed chain (exponents 0..255 available)
    if N < (1 << 256) and mulchain(N) is FD.INF:
        good.append(N)
print('candidate traces:', sorted(cands))
print('orders N annihilating G:', good)
json.dump({'N': [str(x) for x in good]}, open(K + '/order.json', 'w'))
